var users;
users = [];
var user1;
user1 = { name: "ratan", id: 101 };
users.push(user1);
var user2;
user2 = { name: "lucky", id: 102 };
users.push(user2);
var user3;
user3 = { name: "ratan", id: 103 };
users.push(user3);
console.log(users);
